this is job 121679 with task 4
{'path': 'data/pems-bay.h5', 'sensors': 325, 'freq': '5Min', 'make_plots': False, 'normalize': True, 'train_predictor': True, 'prediction_length': 12, 'estimator': 'TempFlow', 'layers': 2, 'cells': 40, 'cell_type': 'LSTM', 'flow': 'RealNVP', 'blocks': 3, 'hidden_size': 100, 'num_hidden': 2, 'conditioning': 200, 'dropout_rate': 0.1, 'serialize_path': 'results/Pems/TF-combine/', 'params': ['layers', 'cells', 'blocks', 'hidden_size', 'num_hidden', 'conditioning', 'dropout_rate'], 'start': [1, 2, 1, 10, 1, 10, 0.05], 'step': [1, 5, 1, 10, 1, 25, 0.05], 'end': [11, 60, 10, 150, 10, 275, 0.55]}
/user/student.aau.dk/raster16/.local/lib/python3.8/site-packages/gluonts/json.py:45: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
  warnings.warn(
Traceback (most recent call last):
  File "/src/main.py", line 40, in <module>
    train, valid, test = hg.load_h5_to_gluon(md['path'], md)
  File "/src/h5_to_gluonts.py", line 13, in load_h5_to_gluon
    store = pd.HDFStore(path)
  File "/user/student.aau.dk/raster16/.local/lib/python3.8/site-packages/pandas/io/pytables.py", line 561, in __init__
    self.open(mode=mode, **kwargs)
  File "/user/student.aau.dk/raster16/.local/lib/python3.8/site-packages/pandas/io/pytables.py", line 710, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/user/student.aau.dk/raster16/.local/lib/python3.8/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/user/student.aau.dk/raster16/.local/lib/python3.8/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file 'data/pems-bay.h5'
srun: error: nv-ai-01.srv.aau.dk: task 0: Exited with exit code 1
finished successful
